### ISSUE TITLE
SDRAM access timing adjustement in firmware v1.x

### ISSUE THREAD

**Issue by cafe-alpha** [hitomi2500/wasca#2]
Long time no see ! Pseudo Saturn Kai development reached a milestone big enough so that I can finally put more time on Wasca development.

And, as indicated in the title, I'm currently experiencing SDRAM access issues in firmware v1.x (MAX 10-based) from a design to another, which improves by randomly changing settings in Qsys and heavy prayings ... in simpler words, I'm flooded with technical difficulty of firmware development.

So I would like to know how you managed to adjust access timing for SDRAM in v1.0 board (which was running Saturn test utility from emulated boot ROM, hence with working SDRAM access) : from my limited understanding, as this requires to dedicate one clock signal for SDRAM chip (and adjust its phase with slack from address/data signals), I was thinking to use second clock output from MAX10's PLL as clock signal for SDRAM.
But firmware v1.0/v1.1 uses only one clock output from PLL, so if there's another way to adjust SDRAM access timing, please inform me about it.

I suppose you still prefer the snickerdoodle-based architecture, but that would be really appreciated if you want to give an hand on MAX 10 one ♪

**Comment by hitomi2500** [comment]
Just thought about commenting on this one. I actually never fine-tuned any hard timings or pin delays, it worked magically as it was. Yes, there was some qsys config involved, but it was only about CAS latency and other timings from datasheet. Basically, it's the second page of the sdram controller setup. 
As far as i understand, the sdram controller expects its clock to be the same as memory IC clock, and it does the data-to-clock phase alignement (basically just latching with a negative clock edge at the i/o) itself.

**Comment by cafe-alpha** [comment]
Thank you for the reply. I honestly don't remember in detail which kind of problem I had at the moment I wrote this issue, but it was either me having troubles to read the datasheet or incorrectly soldering things on the PCB ? Or maybe it was more likely to occur when SPI component was added ?
Now, I no longer have such kind of problem, but it's also a long time I didn't tested on my own board. I can't wait to try your design on it !

**Comment by hitomi2500** [comment]
I suppose i will close this one.
